<?php

namespace App\Http\Middleware;

use App\Models\Device;
use Closure;
use Illuminate\Http\Request;

/**
 * Authenticates Android app API calls using a per-device API key.
 * The key is generated by admin when pre-registering a device,
 * then embedded in the QR provisioning JSON.
 *
 * Header: X-Device-Key: {api_key}
 */
class DeviceApiAuth
{
    public function handle(Request $request, Closure $next)
    {
        $key = $request->header('X-Device-Key');

        if (! $key) {
            return response()->json(['error' => 'Missing device API key.'], 401);
        }

        $device = Device::where('api_key', $key)->first();

        if (! $device) {
            return response()->json(['error' => 'Invalid device key.'], 401);
        }

        // Bind device to request so controllers can access it
        $request->merge(['_authenticated_device' => $device]);
        $request->attributes->set('device', $device);

        return $next($request);
    }
}
